peststagram/common/urls.py
from django.urls import path
from peststagram.common.views import like_functionality, copy_link_to_clipboard, add_comment, IndexPageView

urlpatterns = [
    path('', IndexPageView.as_view(), name="home"),
    path('like/<int:photo_id>/', like_functionality, name="like"),
    path('share/<int:photo_id>/', copy_link_to_clipboard, name="share"),
    path('comment/<int:photo_id>/', add_comment, name="comment"),
]

peststagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("peststagram.common.urls")),
    path('accounts/', include("peststagram.accounts.urls")),
    path('pests/', include("peststagram.pests.urls")),
    path('photos/', include("peststagram.photos.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peststagram/common/models.py
from django.db import models

from peststagram.photos.models import Photo


class Comment(models.Model):
    MAX_TEXT_LENGTH = 300

    text = models.TextField(max_length=MAX_TEXT_LENGTH)
    date_time_of_publication = models.DateTimeField(auto_now_add=True)
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-date_time_of_publication"]


class Like(models.Model):
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

peststagram/common/forms.py
from django import forms
from peststagram.common.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        widgets = {
            "text": forms.Textarea(attrs={"placeholder": "Add comment..."})
        }


class SearchForm(forms.Form):
    pest_name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by pest name...",
            }
        )
    )

peststagram/common/views.py
from django.shortcuts import render, redirect, resolve_url
from django.http import HttpRequest, HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from pyperclip import copy
from peststagram.common.models import Like
from peststagram.common.forms import CommentForm, SearchForm
from peststagram.photos.models import Photo


def index(request: HttpRequest) -> HttpResponse:
    all_photos = Photo.objects.all()
    comment_form = CommentForm()
    search_form = SearchForm(request.GET)

    if search_form.is_valid():
        all_photos = all_photos.filter(
            tagged_pests__name__icontains=search_form.cleaned_data["pest_name"],
        )

    photos_per_page = 1
    paginator = Paginator(all_photos, photos_per_page)
    page = request.GET.get("page")

    try:
        all_photos = paginator.page(page)
    except PageNotAnInteger:
        all_photos = paginator.page(1)
    except EmptyPage:
        all_photos = paginator.page(paginator.num_pages)

    context = {
        "all_photos": all_photos,
        "comment_form": comment_form,
        "search_form": search_form,
    }

    return render(request, "common/home_page.html", context=context)


class IndexPageView(ListView):
    model = Photo
    template_name = "common/home_page.html"
    context_object_name = "all_photos"
    paginate_by = 1

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentForm()
        context["search_form"] = SearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        pest_name = self.request.GET.get("pest_name")

        if pest_name:
            self.request.session["pest_name"] = pest_name
        else:
            self.request.session.pop("pest_name", None)

        pest_name_session = self.request.session.get("pest_name_session")

        if pest_name:
            queryset = queryset.filter(tagged_pests__name__icontains=pest_name)

        return queryset.order_by("date_of_publication")


def like_functionality(request: HttpRequest, photo_id: int) -> HttpResponse:
    try:
        photo = Photo.objects.get(id=photo_id)
        liked_photo = Like.objects.filter(to_photo_id=photo_id).first()

        if liked_photo:
            liked_photo.delete()
        else:
            like = Like(to_photo=photo)
            like.save()

        return redirect(request.META["HTTP_REFERER"] + f"#{photo_id}")

    except Photo.DoesNotExist:
        return redirect(request.META["HTTP_REFERER"])


def copy_link_to_clipboard(request: HttpRequest, photo_id: int) -> HttpResponse:
    copy(request.META["HTTP_HOST"] + resolve_url("details_photo", photo_id))
    return redirect(request.META["HTTP_REFERER"] + f"#{photo_id}")


def add_comment(request: HttpRequest, photo_id: int) -> HttpResponse:
    try:
        photo = Photo.objects.get(id=photo_id)
        form = CommentForm(request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_photo = photo
            comment.save()

        return redirect(request.META["HTTP_REFERER"] + f"#{photo_id}")

    except Photo.DoesNotExist:
        return redirect(request.META["HTTP_REFERER"] + f"#{photo_id}")

templates/common/add_comment.html
<div class="addComments">
    <form method="post" action="{% url 'comment' photo.id %}">
        {% csrf_token %}
        {{ comment_form }}
        <button type="submit">Post</button>
    </form>
</div>

templates/common/home_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pestagram{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-9">

            <!-- Start Searchbar Form -->
            <form class="searchbar" method="get">
                {% csrf_token %}
                {{ search_form }}
                <button>
                    <img src="{% static 'images/search.png' %}" height="18" alt="img2">
                </button>
            </form>
            <!-- End Searchbar Form -->
            {% include "common/pest_photos.html" %}
            
            {% include "common/pest_photos_paginator.html" %}
        </div>
    </div>
    
{% endblock %}

templates/common/pest_photos.html
{% load static %}


    {% for photo in page_obj %}
        <div class="card">
        <p>
        {% if photo.location %}
            <span>{{ photo.location }}</span>
        {% endif %}
        
        <div class="imgBx" id="{{ photo.id }}">
            <img src="{{ photo.picture.url }}" alt="post" class="cover">
        </div>
        
        {% for pest in photo.tagged_pests.all %}
            <a href="{% url 'details_pest' 'username' pest.slug %}">
                <p class="message">
                    <b>{{ pest.name }}</b>
                </p>
            </a>
        {% endfor %}
        
        <a href="{% url 'details_photo' photo.pk %}">
        <h4 class="details">See details</h4>
        </a>
        <div class="button">
        {% include "common/photo_like.html" %}
        <a href="{% url 'share' photo.id %}">
            <i class="fa-solid fa-share"></i>
        </a>
        </div>
            {% include "common/add_comment.html" %}
        </div>
    {% endfor %}

{#                <div class="top">#}
{#                    <div class="userDetails">#}
{#                        <a href="#">#}
{#                            <div class="profilepic">#}
{#                                <div class="profile_img">#}
{#                                    <div class="image">#}
{#                                        <img src="{% static 'images/person.png' %}" alt="img8">#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </a>#}
{#                        <h3>#}
{#                            <a href="#">#}
{#                                Diyan Kalaydzhiev#}
{#                            </a>#}
{#                            <br>#}
{#                            <span>Bansko, Bulgaria</span>#}
{#                        </h3>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="imgBx" id="place the id of the photo here">#}
{#                    <img src="{% static 'images/axolotl.jpeg' %}" alt="post" class="cover">#}
{#                </div>#}
{##}
{#                <div class="bottom">#}
{#                    <div class="actionBtns">#}
{#                        <div class="left">#}
{#                            <span class="heart">#}
{#                                <a href="#">#}
{#                                    <i class="fa-solid fa-heart" style="color: #ed4040;"></i>#}
{#                                    <i class="fa-regular fa-heart"></i>#}
{#                                </a>#}
{#                            </span>#}
{#                            <a href="#">#}
{#                                <i class="fa-solid fa-share"></i>#}
{#                            </a>#}
{##}
{#                        </div>#}
{#                    </div>#}
{#                    <p class="likes">203 likes</p>#}
{##}
{##}
{#                    <a href="#">#}
{#                        <p class="message">#}
{#                            <b>Sasho</b>#}
{#                        </p>#}
{#                    </a>#}
{##}
{#                    <a href="#">#}
{#                        <p class="message">#}
{#                            <b>Some other fish</b>#}
{#                        </p>#}
{#                    </a>#}
{##}
{#                    <a href="#">#}
{#                        <h4 class="details">See details</h4>#}
{#                    </a>#}
{##}
{#                    <h5 class="postTime">19/09/2022</h5>#}
{##}
{#                    <div class="addComments">#}
{##}
{#                        <form method="post" action="#">#}
{#                            <label for="id_body">Body:</label>#}
{#                            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"#}
{#                                      required="" id="id_body"></textarea>#}
{#                            <button type="submit">Post</button>#}
{#                        </form>#}
{##}
{#                    </div>#}
{##}
{#                </div>#}
{#            </div>#}

templates/common/pest_photos_paginator.html
{% load static %}
<div class="pagination">
    <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    <span class="step-links-buttons">
        {% if page_obj.has_previous and page_obj.has_next %}
            <a href="?page={{ page_obj.previous_page_number }}"
                {% if request.GET.pest_name %}
                    &pest_name="{{ request.GET.pest_name }}"
                {% endif %}>
                <i class="fa-solid fa-arrow-left"></i>
            </a>
            <a href="?page={{ page_obj.next_page_number }}"
            {% if request.GET.pest_name %}
                    &pest_name="{{ request.GET.pest_name }}"
                {% endif %}>
                <i class="fa-solid fa-arrow-right"></i>
            </a>

        {% elif page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
            {% if request.GET.pest_name %}
                    &pest_name="{{ request.GET.pest_name }}"
                {% endif %}>
                <i class="fa-solid fa-arrow-left"></i>
            </a>

        {% elif page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
            {% if request.GET.pest_name %}
                    &pest_name="{{ request.GET.pest_name }}"
                {% endif %}>
                <i class="fa-solid fa-arrow-right"></i>
            </a>
        {% endif %}
    </span>
</div>

templates/common/photo_like.html
    <div class="actionBtns">
        <div class="left">
            <span class="heat">
                <a href="{% url 'like' photo.id %}">
                    {% if photo.like_set.all %}
                        <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                    {% else %}
                        <i class="fa-regular fa-heart"></i>
                    {% endif %}
                <p class="likes">{{ photo.like_set.count }} likes</p>
                </a>
            </span>
        </div>
    </div>