peststagram/photos/urls.py
from django.urls import path, include
from peststagram.photos.views import add_photo, details_photo, edit_photo, delete_photo

urlpatterns = [
    path('add/', add_photo, name="add_photo"),
    path('<int:pk>/', include(
        [
            path('', details_photo, name="details_photo"),
            path('edit/', edit_photo, name="edit_photo"),
            path('delete/', delete_photo, name="delete_photo"),
        ]
    ),
         ),
]

peststagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("peststagram.common.urls")),
    path('accounts/', include("peststagram.accounts.urls")),
    path('pests/', include("peststagram.pests.urls")),
    path('photos/', include("peststagram.photos.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peststagram/photos/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from peststagram.photos.validators import validate_photo_size
from peststagram.pests.models import Pest


class Photo(models.Model):
    MAX_NAME_LENGTH = 20

    MAX_DESCRIPTION_LENGTH = 300
    MIN_DESCRIPTION_LENGTH = 10

    MAX_LOCATION_LENGTH = 30

    name = models.CharField(max_length=MAX_NAME_LENGTH)
    picture = models.ImageField(upload_to="photos/", validators=(validate_photo_size,))
    description = models.TextField(
        max_length=MAX_DESCRIPTION_LENGTH,
        validators=(MinLengthValidator(MIN_DESCRIPTION_LENGTH),),
        blank=True,
        null=True,
    )
    location = models.CharField(max_length=MAX_LOCATION_LENGTH, blank=True, null=True)
    tagged_pests = models.ManyToManyField(Pest, blank=True, related_name="tagged_pests")
    date_of_publication = models.DateField(auto_now_add=True)
    time_of_modification = models.DateTimeField(auto_now=True)

peststagram/photos/forms.py
from django import forms
from peststagram.photos.models import Photo


class PhotoCreateForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["name", "picture", "description", "location", "tagged_pests"]


class PhotoEditForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ["picture", "date_created", "time_created"]

peststagram/photos/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from peststagram.common.views import CommentForm
from peststagram.photos.forms import PhotoCreateForm, PhotoEditForm
from peststagram.photos.models import Photo


def add_photo(request: HttpRequest) -> HttpResponse:
    form = PhotoCreateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect("home")

    else:
        context = {
            "form": form,
        }
        return render(request, "photos/photo_add_page.html", context)


def details_photo(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        photo = Photo.objects.get(pk=pk)
        likes = photo.like_set.all()
        comments = photo.comment_set.all()
        comment_form = CommentForm()

        context = {
            "photo": photo,
            "likes": likes,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, "photos/photo_details_page.html", context)

    except ObjectDoesNotExist:
        return redirect("home")


def edit_photo(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        photo = Photo.objects.get(pk=pk)
        form = PhotoEditForm(request.POST or None, instance=photo)
        if form.is_valid():
            form.save()
            return redirect('details_photo', pk=pk)

        else:
            context = {
                "form": form,
                "photo": photo,
            }
            return render(request, "photos/photo_edit_page.html", context)

    except ObjectDoesNotExist:
        return redirect("home")


def delete_photo(request: HttpRequest, pk: int) -> HttpResponse:
    try:
        photo = Photo.objects.get(pk=pk)
        photo.delete()
        return redirect("home")

    except ObjectDoesNotExist:
        return redirect("home")

templates/photos/photo-details-page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <title>Peststagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="{% url 'home' %}">
                    <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="{% url 'home' %}">
                    <i>Peststagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pest Page -->
                        <a href="#">
                            <i>Add Pest</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Log out -->
                        <a href="#">
                            <i>Log out</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <div class="container">
        <div class="col-9">

            <!-- Start Pest Photo Post Section -->
            <div class="card">
                <div class="top">

                    <!-- Start User Details and Image Location Section -->
                    <div class="userDetails">

                        <!-- Link to User Profile Details Page-->
                        <a href="#">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>

                            <!-- Link to User Profile Details Page -->
                            <a href="#">
                                <!-- IF user has first name and last name -->
                                Diyan Kalaydzhiev
                                <!-- else -->
                                <!-- show user username -->
                            </a>
                            <br>

                            <!-- IF the photo has location -->
                            <span>Bansko, Bulgaria</span>

                            <!-- IF the viewer is the creator of the photo -->
                            <div class="edit-delete-btns">

                                <!-- Link to Edit Pest Photo Page -->
                                <a href="#">
                                    <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                         alt="edit button">
                                </a>

                                <!-- Link to Delete Pest Photo Page -->
                                <a href="#">
                                    <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                                </a>
                            </div>
                            <!-- End IF the viewer is the creator of the photo -->

                        </h3>
                    </div>
                    <!-- End User Details and Image Location Section -->

                </div>

                <!-- Start Pest Photo -->
                <div class="imgBx" id="place the id of the photo here">
                    <!-- Pest Photo -->
                    <img src="{% static 'images/axolotl.jpeg' %}" alt="post" class="cover">
                </div>
                <!-- End Pest Photo -->

                <div class="bottom">

                    <!-- Start Like and Share Buttons Section -->
                    <div class="actionBtns">
                        <div class="left">

                            <!-- Start Like Button -->
                            <span class="heart">

                                    <!-- Link to Like Path -->
                                    <a href="#">
                                        <!-- if user has liked the photo -->
                                        <!-- <i class="fa-solid fa-heart" style="color: #ed4040;"></i> -->
                                        <!-- else -->
                                        <i class="fa-regular fa-heart"></i>
                                    </a>
                            </span>
                            <!-- End Like Button -->

                            <!-- Start Share  Button -->

                            <!-- Link to Share Path -->
                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>
                        </div>
                    </div>
                    <!-- End Like and Share Buttons Section -->

                    <!-- Number of Likes for the Photo -->
                    <p class="likes">203 likes</p>

                    <!-- Start Tagged Pests Section-->
                    <!-- Link to First Tagged Pest Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Sasho</b>
                        </p>
                    </a>
                    <!-- Link to Second Tagged Pest Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Some other fish</b>
                        </p>
                    </a>
                    <!-- End Tagged Pests Section-->

                    <!-- Photo description -->
                    <p class="pest-details">This is my pest</p>

                    <!-- Date of Publication or edit of the Photo -->
                    <h5 class="postTime">19/09/2022</h5>

                    <!-- Start Comments Section -->
                    <div class="comments">
                        <div class="top">
                            <div class="userDetails">
                                <div class="comment-data">
                                    <div class="profilepic">
                                        <div class="profile_img">
                                            <div class="image">
                                                <!-- User Profile Image -->
                                                <img src="{% static 'images/person.png' %}" alt="img8">
                                            </div>
                                        </div>
                                    </div>
                                    <p>
                                        <!-- Link to User Profile Details Page-->
                                        <!-- User First and/or Last Name or username-->
                                        <a href="">Steven Ivanov</a>
                                        <!-- User Comment -->
                                        - OMG where can i get one
                                    </p>
                                </div>
                                <span>Sept. 20, 2022, 5:02 p.m.</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Comments Section -->
                </div>

                <!-- Start Add Comments Section -->
                <div class="addComments">

                    <!-- Start Add Comments Form -->
                    <form method="post" action="#">
                        <label for="id_body">Body:</label>
                        <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                  required="" id="id_body"></textarea>
                        <!-- Post Comments Button -->
                        <button type="submit">Post</button>
                    </form>
                    <!-- End Add Comments Form -->

                </div>
                <!-- End Add Comments Section -->

            </div>
            <!-- End Pest Photo Post Section -->

        </div>
    </div>

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/photos/photo_add_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add Photo{% endblock %}
{% block content %}
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
{% endblock %}

templates/photos/photo_details_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Details Photo{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-9">

            <!-- Start Pest Photo Post Section -->
            <div class="card">
                <div class="top">

                    <!-- Start User Details and Image Location Section -->
                    <div class="userDetails">

                        <!-- Link to User Profile Details Page-->
                        <a href="#">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>

                            <!-- Link to User Profile Details Page -->
                            <a href="#">
                                <!-- IF user has first name and last name -->
                                Diyan Kalaydzhiev
                                <!-- else -->
                                <!-- show user username -->
                            </a>
                            <br>

                            <!-- IF the photo has location -->
                            {% if photo.location %}
                            <span>{{ photo.location }}</span>
                            {% endif %}

                            <!-- IF the viewer is the creator of the photo -->
                            <div class="edit-delete-btns">

                                <!-- Link to Edit Pest Photo Page -->
                                <a href="{% url 'edit_photo' photo.pk %}">
                                    <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                         alt="edit button">
                                </a>

                                <!-- Link to Delete Pest Photo Page -->
                                <a href="{% url 'delete_photo' photo.pk %}">
                                    <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                                </a>
                            </div>
                            <!-- End IF the viewer is the creator of the photo -->

                        </h3>
                    </div>
                    <!-- End User Details and Image Location Section -->

                </div>

                <!-- Start Pest Photo -->
                <div class="imgBx" id="place the id of the photo here">
                    <!-- Pest Photo -->
                    <img src="{{ photo.picture.url }}" alt="post" class="cover">
                </div>
                <!-- End Pest Photo -->

                <div class="bottom">

                    <!-- Start Like and Share Buttons Section -->
                    {% include 'common/photo_like.html' %}
                    <a href="{% url 'share' photo.id %}">
                        <i class="fa-solid fa_share"></i>
                    </a>
                    <!-- End Like and Share Buttons Section -->

                    <!-- Start Tagged Pests Section-->
                    <!-- Link to First Tagged Pest Details Page -->
                    {% for pest in photo.tagged_pests.all %}
                        <a href="{% url 'details_pest' pest.slug %}">
                            <p class="message">
                                <b>{{ pest.name }}</b>
                            </p>
                        </a>
                    {% endfor %}
                    <!-- End Tagged Pests Section-->

                    <!-- Photo description -->
                    <p class="pest-details">This is my pest</p>

                    <!-- Date of Publication or edit of the Photo -->
                    <h5 class="postTime">{{ photo.date_of_publication }}</h5>

                    <!-- Start Comments Section -->
                    {% for comment in comments %}
                        <div class="comments">
                            <div class="top">
                                <div class="userDetails">
                                    <div class="comment-data">
                                        <div class="profilepic">
                                            <div class="profile_img">
                                                <div class="image">
                                                    <img src="{% static 'images/person.png' %}" alt="img8">
                                                </div>
                                            </div>
                                        </div>
                                        <p>
                                            <a href="">Test Name</a>
                                            {{ comment.text }}
                                        </p>
                                    </div>
                                    <span>{{ comment.date_time_of_publication }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- End Comments Section -->
                </div>

                <!-- Start Add Comments Section -->
                <div class="addComments">

                    <!-- Start Add Comments Form -->
                    <form method="post" action="#">
                        <label for="id_body">Body:</label>
                        <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                  required="" id="id_body"></textarea>
                        <!-- Post Comments Button -->
                        <button type="submit">Post</button>
                    </form>
                    <!-- End Add Comments Form -->

                </div>
                <!-- End Add Comments Section -->

            </div>
            <!-- End Pest Photo Post Section -->

        </div>
    </div>
{% endblock %}

templates/photos/photo_edit_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}Edit Photo{% endblock %}
{% block content %}
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pests">Tag Pests:</label>

                <select name="pests" id="id_tagged_pests" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
{% endblock %}